name: Update data
on: 
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  fetch-and-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch and commit
        run: |
          mkdir -p data
          wget https://pibs.nats.co.uk/operational/pibs/PIB.xml -O data/PIB.xml
          git add data

          mkdir -p html
          wget http://pibs.nats.co.uk/operational/pibs/pib3.shtml -O html/pib3.shtml
          wget http://pibs.nats.co.uk/operational/pibs/pib4.shtml -O html/pib4.shtml
          wget http://pibs.nats.co.uk/operational/pibs/pib5.shtml -O html/pib5.shtml
          wget http://pibs.nats.co.uk/operational/pibs/pib6.shtml -O html/pib6.shtml
          wget http://pibs.nats.co.uk/operational/pibs/pib54n.shtml -O html/pib54n.shtml
          wget http://pibs.nats.co.uk/operational/pibs/pib53n.shtml -O html/pib53n.shtml
          wget http://pibs.nats.co.uk/operational/pibs/pib52n.shtml -O html/pib52n.shtml
          wget http://pibs.nats.co.uk/operational/pibs/pib51n.shtml -O html/pib51n.shtml
          wget http://pibs.nats.co.uk/operational/pibs/pib50n.shtml -O html/pib50n.shtml
          git add html

          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatic NOTAM data update"
            git push
          fi
